language: python

os: linux
dist: xenial

addons:
  postgresql: 9.6
  apt:
    packages:
      - postgresql-9.6-postgis-2.4
      - python2.7-dev
      - python3-dev
      - autotools-dev
      - libexpat1-dev
      - libfreexl-dev
      - libgeos-dev
      - libproj-dev
      - libreadline-dev
      - libsqlite3-dev
      - libsqlite3-mod-spatialite
      - libxml2-dev
      - zlib1g-dev

notifications:
  email:
    on_failure: change

services:
  - postgresql

jobs:
  include:
    - python: 2.7
      env:
      - TOX_ENV=py27
    - python: 3.5
      env:
      - TOX_ENV=py35
    - python: 3.6
      env:
      - TOX_ENV=py36
    - python: 3.7
      env:
      - TOX_ENV=py37
    - python: 3.8
      env:
      - TOX_ENV=py38
    - python: pypy3
      env:
      - TOX_ENV=pypy

env:
  global:
    - SPATIALITE_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu/mod_spatialite.so"

install:
  # Install tox
  - pip install tox

  # Install flake8 style checker
  - pip install -r requirements.txt

before_script:
  # Create database user "gis"
  - psql -c "CREATE ROLE gis PASSWORD 'gis' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;" -U postgres

  # Create database "gis"
  - psql -c 'CREATE DATABASE gis;' -U postgres

  # Create schema "gis" into database "gis"
  - psql -d gis -c 'CREATE SCHEMA gis;' -U postgres

  # Grant CREATE permission on database "gis" to role "gis"
  - psql -c 'GRANT CREATE ON DATABASE gis TO "gis";' -U postgres

  # Grant USAGE and CREATE permission on schema "gis" to role "gis"
  - psql -d gis -c 'GRANT USAGE,CREATE ON SCHEMA gis TO "gis";' -U postgres

  # Add PostGIS extension to "gis" database
  - psql -d gis -c 'CREATE EXTENSION postgis;' -U postgres

script:
  # Run the library through flake8
  - flake8 --ignore=W503,W504 geoalchemy2 tests

  # Run the unit test suite with SQLAlchemy=1.1.2
  - tox -e $TOX_ENV-sqla11 --sitepackages -- -v --cov geoalchemy2 --cov-report term-missing

  # Run the unit test suite with the latest version of SQLAlchemy
  - tox -e $TOX_ENV-sqlalatest --sitepackages -- -v --cov geoalchemy2 --cov-report term-missing

after_script:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  username: erilem
  password:
    secure: eYqYIWlsCp/awFekONU9fRKjYeleO49rzf2qWNYG3HxWvp8+1mgjLubnMTIARHiKbB6/iF3PEfGQd7+ICIi6dxWQFxWaBu7HOFaOu0wOXweNbrwhDqKrnJRJ3/2CPRTlYARr7uJhXrVTQVOIC//mEtUX7atF5EVs8fW8BM3/iT0=
  on:
    tags: true
    repo: geoalchemy/geoalchemy2
