language: python

python:
  - 2.7
  - 3.3

notifications:
  email:
    on_failure: change

services:
  - postgresql

env:
  - POSTGIS_VERSION=1.5
  - POSTGIS_VERSION=2.0.3

install:
  - if [[ "$POSTGIS_VERSION" == "1.5" ]]; then sudo apt-get install postgresql-9.1-postgis -q; fi
  - if [[ "$POSTGIS_VERSION" != "1.5" ]]; then sudo apt-get install build-essential postgresql-9.1 postgresql-server-dev-9.1 libxml2-dev libproj-dev libjson0-dev libgeos-dev xsltproc docbook-xsl docbook-mathml; fi
  - if [[ "$POSTGIS_VERSION" != "1.5" ]]; then wget http://download.osgeo.org/postgis/source/postgis-$POSTGIS_VERSION.tar.gz; fi
  - if [[ "$POSTGIS_VERSION" != "1.5" ]]; then tar xfvz postgis-$POSTGIS_VERSION.tar.gz; fi
  - if [[ "$POSTGIS_VERSION" != "1.5" ]]; then cd postgis-$POSTGIS_VERSION; fi
  - if [[ "$POSTGIS_VERSION" != "1.5" ]]; then ./configure --without-topology --without-raster; fi
  - if [[ "$POSTGIS_VERSION" != "1.5" ]]; then make; fi
  - if [[ "$POSTGIS_VERSION" != "1.5" ]]; then sudo make install; fi
  - if [[ "$POSTGIS_VERSION" != "1.5" ]]; then cd ..; fi

before_script:
  - psql -c "CREATE ROLE gis PASSWORD 'gis' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;" -U postgres
  - psql -c 'CREATE DATABASE gis;' -U postgres
  - if [[ "$POSTGIS_VERSION" == "1.5" ]]; then psql -d gis -U postgres -f /usr/share/postgresql/9.1/contrib/postgis-1.5/postgis.sql; fi
  - if [[ "$POSTGIS_VERSION" == "1.5" ]]; then psql -d gis -U postgres -f /usr/share/postgresql/9.1/contrib/postgis-1.5/spatial_ref_sys.sql; fi
  - if [[ "$POSTGIS_VERSION" != "1.5" ]]; then psql -d gis -U postgres -f /usr/share/postgresql/9.1/contrib/postgis-2.0/postgis.sql; fi
  - if [[ "$POSTGIS_VERSION" != "1.5" ]]; then psql -d gis -U postgres -f /usr/share/postgresql/9.1/contrib/postgis-2.0/spatial_ref_sys.sql; fi

script:
  - python setup.py nosetests -v

after_script:
  - pip install coveralls
  - coveralls
