language: python

python:
  - 2.7

notifications:
  email:
    on_failure: change

services:
  - postgresql

env:
  - TOX_ENV=py27sqla11 POSTGIS_VERSION=1.5
  - TOX_ENV=py27sqla11 POSTGIS_VERSION=2
  - TOX_ENV=py33sqla11 POSTGIS_VERSION=1.5
  - TOX_ENV=py33sqla11 POSTGIS_VERSION=2
  - TOX_ENV=py34sqla11 POSTGIS_VERSION=1.5
  - TOX_ENV=py34sqla11 POSTGIS_VERSION=2
  - TOX_ENV=pypysqla11 POSTGIS_VERSION=1.5
  - TOX_ENV=pypysqla11 POSTGIS_VERSION=2

matrix:
  include:
    - python: 3.5
      env:
      - TOX_ENV=py35sqla11 POSTGIS_VERSION=1.5
    - python: 3.5
      env:
      - TOX_ENV=py35sqla11 POSTGIS_VERSION=2

install:
  # Install PostGIS 1.5
  - if [[ "$POSTGIS_VERSION" == "1.5" ]]; then sudo apt-get install -y --force-yes postgresql-9.1-postgis=1.5.3-2 postgis=1.5.3-2; fi

  # Install tox
  - pip install tox

  # Install flake8 style checker
  - pip install -r requirements.txt

before_script:
  # Create database user "gis"
  - psql -c "CREATE ROLE gis PASSWORD 'gis' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;" -U postgres

  # Create database "gis"
  - psql -c 'CREATE DATABASE gis;' -U postgres

  # Create schema "gis" into database "gis"
  - psql -d gis -c 'CREATE SCHEMA gis;' -U postgres

  # Grant CREATE permission on database "gis" to role "gis"
  - psql -c 'GRANT CREATE ON DATABASE gis TO "gis";' -U postgres

  # Grant USAGE and CREATE permission on schema "gis" to role "gis"
  - psql -d gis -c 'GRANT USAGE,CREATE ON SCHEMA gis TO "gis";' -U postgres

  # Add PostGIS extension to "gis" database
  - if [[ "$POSTGIS_VERSION" == "1.5" ]]; then psql -d gis -U postgres -f /usr/share/postgresql/9.1/contrib/postgis-1.5/postgis.sql; fi
  - if [[ "$POSTGIS_VERSION" == "1.5" ]]; then psql -d gis -U postgres -f /usr/share/postgresql/9.1/contrib/postgis-1.5/spatial_ref_sys.sql; fi
  - if [[ "$POSTGIS_VERSION" != "1.5" ]]; then psql -d gis -U postgres -c "CREATE EXTENSION postgis;"; fi

script:
  # Run the library through flake8
  - flake8 geoalchemy2 tests --ignore=E711

  # Run the unit test suite
  - tox -e $TOX_ENV --sitepackages -- -v --cov geoalchemy2 --cov-report term-missing

after_script:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: erilem
  password:
    secure: eYqYIWlsCp/awFekONU9fRKjYeleO49rzf2qWNYG3HxWvp8+1mgjLubnMTIARHiKbB6/iF3PEfGQd7+ICIi6dxWQFxWaBu7HOFaOu0wOXweNbrwhDqKrnJRJ3/2CPRTlYARr7uJhXrVTQVOIC//mEtUX7atF5EVs8fW8BM3/iT0=
  on:
    tags: true
    repo: geoalchemy/geoalchemy2
